### PR TITLE
Firmware patch v2

### PR DESCRIPTION
**Pull request by rallepalaveev**
An optimized patched firmware.

### CODE REVIEW

**Comment by tjboldt** [comment]
Thanks for your efforts. You have done some amazing work and it is greatly appreciated. I’ll take a look at what changes you made here but at this time, I will likely not merge in another binary patch. I disassembled your last firmware update, modified it and updated the source code. All further changes should be made to the source code for everyone’s benefit rather than just binary changes. Would you be willing to update the source? I made new hardware (that should arrive this week) and will be doing further testing before merging the block0001 branch into main. Have a look here: https://github.com/tjboldt/ProDOS-ROM-Drive/blob/block0001/Firmware/Firmware.asm

**Comment by rallepalaveev** [comment]
Hi Terence,

The v2 of the firmware is almost identical to the original I wrote. Here is the list of changes:

1. The most important change is that I put zeroes in locations $CnFC and $CnFD which I found to be a requirement in a ProDOS technical guide. These locations must either contain the number of available blocks or, if zeroed - instruct ProDOS to query the driver with a STATUS request for the available blocks. 

2. A minor change - I only left one instance of the JMP ($00FA) instruction - the first one. The rest I changed to conditional branches, which are always true and point to the JMP. In this way I save one byte per JMP. It may ot be  big deal but it is good coding practice when squeezing code in 256 bytes!

Re source - I write directly into machine code, I can certainly update the source too, so it loos nice and readable, after you have dome most of the work. :)

Finally, this new version should be OK with the new hardware.

Best regards and happy holidays!

Ralle

**Comment by rallepalaveev** [comment]
One more comment - I just looked at the source and line 35 should be an LDY #$00 (as in the binary), so that at line 40 onward the STY commands are correct, otherwise Y's value is unknown.

**Comment by tjboldt** [comment]
Thanks. I had those bytes as zeros already when I disassembled your code and merged with my source.

	.byte      0,0     ;0000 blocks = check status
	.byte      3       ;bit 0=read 1=status
	.byte     entry&$00FF ;low byte of entry

I'll hopefully have time to test this week and integrate your branch improvements. It's definitely worth the challenge of optimization when working such a tiny firmware space.

**Comment by tjboldt** [comment]
> One more comment - I just looked at the source and line 35 should be an LDY #$00 (as in the binary), so that at line 40 onward the STY commands are correct, otherwise Y's value is unknown.

Thanks. I missed that when merging disassembler and existing source.

**Comment by tjboldt** [comment]
Closing this pull request as the changes have been made to the source code and merged in another pull request.

**Pull request closed without merging**
